version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: freshtrio-db
    environment:
      POSTGRES_DB: freshtrio
      POSTGRES_USER: freshtrio_user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - freshtrio-network

  backend:
    build: ./backend
    container_name: freshtrio-api
    environment:
      SPRING_PROFILES_ACTIVE: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: freshtrio
      DB_USERNAME: freshtrio_user
      DB_PASSWORD: password
      JWT_SECRET: ${JWT_SECRET}
      FCM_KEY_PATH: ${FCM_KEY_PATH}
      UPLOAD_DIR: /app/uploads
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - uploads:/app/uploads
      - ./fcm-key.json:/app/fcm-key.json
    networks:
      - freshtrio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: freshtrio-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - uploads:/var/www/uploads
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - freshtrio-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: freshtrio-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  freshtrio-network:
    driver: bridge

volumes:
  postgres_data:
  uploads: