spring:
  application:
    name: freshtrio-api-dev
  
  # Disable database and security for development
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.flywaydb.spring.boot.FlywayAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: false

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.freshtrio: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Development Configuration
app:
  jwt:
    secret: dev-jwt-secret-key-for-development-only-not-secure
    expiration: 86400000 # 24 hours

  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"